# THIS FILE IS ONLY FOR ANSIBLE PUSH METHOD
all:
  children:
    wordpress:
      hosts:
        wp-master-1:
          ansible_host: "{{ remote_server_public_ip }}"
          ansible_connection: ssh
          ansible_user: "{{ username }}"
          ansible_port: "{{ remote_server_ssh_port }}"
        wp-worker-1:
          ansible_host: "{{ remote_server_public_ip }}"
          ansible_connection: ssh
          ansible_user: "{{ username }}"
          ansible_port: "2224"
        wp-worker-2:
          ansible_host: "{{ remote_server_public_ip }}"
          ansible_connection: ssh
          ansible_user: "{{ username }}"
          ansible_port: "2223"
        wp-nginx:
          ansible_host: "{{ remote_server_public_ip }}"
          ansible_connection: ssh
          ansible_user: "{{ username }}"
          ansible_port: "2225"