---
- name: Update and upgrade packages
  apt:
    update_cache: true
    upgrade: safe
    autoremove: true
  changed_when: false # This will never report 'changed' status
  when: ansible_distribution == "Ubuntu" # task will run only on Ubuntu

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  reboot:
    msg: Rebooting due to a kernel update
  when: reboot_required_file.stat.exists

- name: Install packages
  package:
    name: "{{ essential_packages }}"
    state: present

# - name: Set Hostname
#   hostname:
#     name: "{{ remote_server_shortname }}"

# - name: "Add hostname in /etc/hosts"
#   ansible.builtin.lineinfile:
#     path: /etc/hosts
#     insertafter: ^127\.0\.0\.1 *localhost
#     line: "127.0.0.1 {{ remote_server_shortname }}"
#     owner: root
#     group: root
#     mode: '0644'