---
- name: Create a new user with a home directory
  ansible.builtin.user:
    name: "{{ local_username }}"
    create_home: yes
    password: "{{ local_username_password | password_hash('sha512') }}"
  become: true

- name: Set the name of a sudo group
  set_fact:
    sudo_group: sudo

- name: Add user to sudo group
  ansible.builtin.user:
    name: "{{ local_username }}"
    groups: "{{ sudo_group }}"
    append: yes
  become: true

- name: Allow '{{ sudo_group }}' group to have passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%{{ sudo_group }}'
    line: '%{{ sudo_group }} ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'
